github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/motherless-downloader",
  "https://serp.co/products/motherless-downloader/reviews/",
  "https://extensions.serp.co/motherless-downloader",
  "https://browserextensions.io/motherless-downloader"
]
